spring.application.name=marketplace-product-service

server.port=8082


spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=2016

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
# ?g?r schemada s?hv varsa, servisin ba?lamas?na mane olmas?n dey?:
spring.graphql.schema.inspection.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

grpc.server.port=9091